language: java
sudo: false # faster builds

before_Start:
    - mvn validate

script: mvn clean verify -P ci_dev

after_success:
after_failure:

git: 
    depth: false


branches: # todo apply filter to only build branches with issue number.?
    only:
    - /.*/