language: java
sudo: false # faster builds

script: mvn clean test -Dtest.regex="(IntegrationTest)" -P ci_dev

after_success:
after_failure:

git: 
    depth: false


branches: # todo apply filter to only build branches with issue number.?
    only:
    - /.*/